// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkV9Mg8Ch3VphphGvMNrJOz0A0MHMJQwQ',
    appId: '1:182457641442:android:687944c7439aae5d65b1bb',
    messagingSenderId: '182457641442',
    projectId: 'yupgagae-app',
    storageBucket: 'yupgagae-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpeW5-_o-tWHa5ZR9FEpsjk04kTqN_V8o',
    appId: '1:182457641442:ios:a03f776c9f33a57565b1bb',
    messagingSenderId: '182457641442',
    projectId: 'yupgagae-app',
    storageBucket: 'yupgagae-app.firebasestorage.app',
    androidClientId: '182457641442-4c04ldcd18f3o1t8b1gheo21i858ei4q.apps.googleusercontent.com',
    iosClientId: '182457641442-nc46uj4i2eeh4cbc998mepuma0fe3u8j.apps.googleusercontent.com',
    iosBundleId: 'com.yupgagae.app',
  );
}
